### ISSUE TITLE
Hiding specific filterable attributes from categs & subcategs

### ISSUE THREAD

**Issue by Florinnn** [jabberdog/Wled#9]
Hi Liam,

As discussed we need a solution that I can use to hide specific attributes from the layered navigation on categs & subcategs. 
I need you to provide me with some schema code I can use to hide the attributes by modifying in back end inside the layout schema. Like this (I know is not a good solution -- is just so you get what I mean I need from you): https://stackoverflow.com/questions/20994703/hiding-or-showing-filters-in-certain-categories-in-magento

Thanks,
Florin

**Comment by jabberdog** [comment]
<reference name="catalog.leftnav">
    <action method="hideAttributes"><code>wled_shop_by_room</code></action>
</reference>

Copy and paste this code into the relevant "Layout Update XML" text box inside the category. Be sure to replace <code>wled_shop_by_room</code> with the relevant attribute that you want to hide in the filter for that category.

<code>wled_shop_by_room</code> = The value inside the <code></code> tags is the Attribute Code. You can find what the attribute code of an attribute is by going to Catalog > Attributes > Manage Attributes.

If you have any questions, let me know.

**Comment by Florinnn** [comment]
All good so far so I will close it.
Thanks,
Florin
